### ISSUE TITLE
IMUの取り付け角度を実機となるべく一致させる

### ISSUE THREAD

**Issue by yosuke** [pwri-opera/OperaSim-PhysX#51]
具体的には、まず建機の姿勢をシミュレータと実機で一致させる。
以下のコマンドを入力する：

```
rostopic echo /zx120/joint_states
```

建機の各関節の角度がposition配列として出力されるので、rosbagの出力とシミュレータの出力が近い値になるように、シミュレータ上で建機の関節角を調整する。

```
name: 
  - left_front_wheel_joint
  - left_middle_wheel_joint
  - left_rear_wheel_joint
  - right_front_wheel_joint
  - right_middle_wheel_joint
  - right_rear_wheel_joint
  - rotator_joint
  - boom_joint
  - arm_joint
  - backet_joint
  - backet_end_joint
position: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.024543690341719326, -0.47391485834558367, 1.5176129840230586, 2.08238580105205, 0.0]
```

次にIMUの取り付け角度をシミュレータと実機で一致させる。
以下のコマンドを入力する：

```
rostopic echo /zx120/boom/g2_imu
```

IMUの値が出力されるが、`linear_acceleration`に重力加速度のxyz成分が出力されるため、この部分に注目する。
linear_accelerationの3つの値が、rosbagの出力とシミュレータの出力で近い値になる様に、シミュレータ上でのIMUの取り付け角度を調整する。

```
linear_acceleration: 
  x: 3.7362850341796876
  y: -0.0059857177734375005
  z: 9.08691815185547
```
